### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by cyberillithid** [lorenzofox3/zora-node#10]
When `{"type": "module"}` is added to `package.json`, `pta` starts failing to import the test modules.

The stack trace isn't very clear:
```
/opt/proj/test/test.js:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/proj/test/test.js
require() of ES modules is not supported.
require() of /opt/proj/test/test.js from /opt/proj/node_modules/pta/src/cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename engram.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/proj//package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1217:13) {
  code: 'ERR_REQUIRE_ESM'
}
```

Presumably discarding this option recovers the `pta` functionality, yet probably there is something that may be done with the novel ES-modules approach, instead of Common-JS?

Just replacing `cli.js` with `cli.mjs` and `spec = requireFn` with `spec = await import` makes the resulting node-cli-script work with ESM, but fail with default CJS approach.

(I'm not very fluent in modern Node, so sorry if this report is unclear.)

**Comment by lorenzofox3** [comment]
Thanks for the report. It is a bit conused for me: do you think you could provide a simple gist with a pacakge.json and a test file so I could try to reporduce and investigate.

Thanks a lot

**Comment by cyberillithid** [comment]
https://gist.github.com/cyberillithid/f751f184527eb187199fd4c89d9ed671
For me this fail-behaviour reproduces on both node-13.10 and fresh 14.5 -- and judging by the docs it may as well function the same way in the LTS node 12, even if ES Modules are deemed there as being still in experimental stage.

**Comment by lorenzofox3** [comment]
thanks. I am going to have a look !

**Comment by lorenzofox3** [comment]
Sorry, I just realized I never had a look. 

I think I can now drop the package [esm](https://www.npmjs.com/package/esm) to use node default behavior. I'll have a look this week end. Ping me If again it slip out of my mind...

**Comment by lorenzofox3** [comment]
fixed 🎉
