### ISSUE TITLE
tsconfig-paths module not loading

### ISSUE THREAD

**Issue by Alexey-Sch** [lorenzofox3/zora-node#11]
```node -r ts-node/register -r tsconfig-paths/register ./node_modules/pta/src/cli.js test.ts```

```
Error: Cannot find module '@core/log'
Require stack:
- test.ts
- node_modules\pta\src\cli.js
    at Object.<anonymous> (test.ts:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'test.ts',
    'node_modules\\pta\\src\\cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! package@0.0.1 test: `node -r ts-node/register -r tsconfig-paths/register ./node_modules/pta/src/cli.js test.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the package@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

test.ts:

```
...
import { Log } from "@core/log";
...
```

tsconfig.json:
```
...
"baseUrl": "./src",
"paths": {
    "@core/*": [ "core/*" ]
},
...
```

Herewith:
```uvu -r ts-node/register -r tsconfig-paths/register test-uvu.ts```
-- runs ok.

**Comment by lorenzofox3** [comment]
Thanks for the report but I am not able to reproduce, can you please provide a minimum sample perhaps based on the [following gist](https://gist.github.com/lorenzofox3/c6ea44dbf9f33c6c9dd7922a2f083d9b)

**Comment by Alexey-Sch** [comment]
A repository with a minimal example: https://github.com/Alexey-Sch/pta-bug.
```npm start``` - works as intended.
```npm test``` - results in error.

**Comment by lorenzofox3** [comment]
you need to tell pta not to use esm package to load modules with the --no-esm flag: 
``ts-node -r tsconfig-paths/register node_modules/pta/src/cli.js --no-esm tests/test.ts``

Also, with pta the format of your test must be slightly different:
```Javascript
export default (t) => {
    log("test test test");

    t.ok(true, "true is truthy");
};
```

<img width="1156" alt="Screenshot 2020-09-30 at 12 36 18" src="https://user-images.githubusercontent.com/2402022/94675170-9b547000-0319-11eb-863f-e9772cd27f96.png">

**Comment by Alexey-Sch** [comment]
Thanks. Maybe it should be described in the readme?

**Comment by lorenzofox3** [comment]
yep you are right. I think I am going to drop pretty soon the esm package in favor of node native implementation
