### ISSUE TITLE
When running with `onchange` the output changes to TAP 13 format

### ISSUE THREAD

**Issue by pke** [lorenzofox3/zora-node#4]
The nice formatted output/reporter is gone when running `pta` under `onchange` like suggested in the readme.

**Comment by lorenzofox3** [comment]
You are right it seems that the terminal looses its TTY nature through ``onchange`` and pta fallback to a TAP stream.

Try [chokidar-cli](http://github.com/kimmobrunfeldt/chokidar-cli) instead of ``onchange``, it seems to work fine (on my terminal at least)
