### ISSUE TITLE
read from stdin, eg. babel

### ISSUE THREAD

**Issue by chiefjester** [lorenzofox3/zora-node#6]
Hi @lorenzofox3,  👋 

I just tried this today. I love what you did here; having a more opinionated workflow in exchange for zero-config is a good trade-off.

I'm trying this out on a typical workflow. I was wondering how I can pipe a **STDOUT** of a program to `pta`'s **STDIN**? My usage would be babel transforms like JSX, which is a bit common to modern development. I know you are not using it, but this would welcome more users if there is an easy way to do it. 

Eg. `babel test.js | pta`

P.S. I tried installing `zora-node` because of the name of the repo, but it was non-existent, took me a few minutes to figure out it was `pta`.

**Comment by chiefjester** [comment]
I've managed to make it work via installing babel-node, it's kinda weird referencing `pta` via `node_modules/.bin` 🤔 ?

`$ babel-node node_modules/.bin/pta`

Opening up STDIN as input would still have better ergonomics though.
1. No need to install babel-node
2. You can just pipe whatever to pta
3. If you can pipe, you don't need to reference pta via `node_modules/.bin` directory.

**Comment by lorenzofox3** [comment]
That would be a bit complicated to implement as pta depends on the file structure. 
Also I am wondering what is the added value: If you use stdin you won't have stack trace for example.

If you use babel. You can simply output the result somewhere on the disk before calling pta:

``babel > some/test/file.js && pta some/test/files.js``

**Comment by chiefjester** [comment]
@lorenzofox3 Hello 👋🏻, Thanks for the response. 🙏🏻The problem with doing that way is I get incorrect code coverage. 

This used to be 100% when tested on jest:
![Alt text](https://monosnap.com/image/Xi8HeUyIsW7VYd7us2yUoZkogakhq1)

I guess what I'm asking is more of direct integration of babel? 🙂

**Comment by lorenzofox3** [comment]
What tool do you use for code instrumentation? Usually they are able to deal with sourcemaps (in you case emitted by babel)

> I guess what I'm asking is more of direct integration of babel? 🙂

this I am sorry but won't happen. pta is a testing library nothing more :), how you generate you testing code is a totally different story. 

By the way I just saw AvA just dropped its built in support for babel

**Comment by lorenzofox3** [comment]
maybe you can provide a gist so I can reproduce and try to help

**Comment by chiefjester** [comment]
Hi @lorenzofox3, 👋🏻 thank you for checking back with me. 🙂

>By the way I just saw AvA just dropped its built-in support for babel

Are you perhaps talking about this [PR](https://github.com/avajs/ava/pull/2319)?

You are right they're removing built-in support and settled for a [separate dependency/package](https://github.com/avajs/babel). So that the core becomes leaner. They still support the direct integration of babel through that newly created [package](https://github.com/avajs/babel).

> maybe you can provide a gist so I can reproduce and try to help

Much appreciated, thank you. 🙇🏻‍♂️ I'm testing it out on an old package of mine, would you mind taking a look? You can clone the [pta branch](https://github.com/ayosdev/react-i18n-map/tree/pta)

**Comment by lorenzofox3** [comment]
[here](https://gist.github.com/lorenzofox3/8d664169d1ee653a4585f1d76da3010a) you go. 

I use ``c8`` instead ``nyc`` (by habits) for the coverage

Seems to work fine. If you wish to have html report instead you can change to ``c8 -r html pta *.test.js``

**Comment by chiefjester** [comment]
@lorenzofox3 

Oh wow, Thank you very much! 🙌🏻 🤝

I haven't thought of that, so the main culprit was `preset-env` and probably the plugin I use for `object-rest-spread`.

So I'm just leaving here, for future me, or other people got stuck as well:

The strategy I'm using is only using two environments (development and production). For tests, it'll default to development, like what you have in the [gist](https://gist.github.com/lorenzofox3/8d664169d1ee653a4585f1d76da3010a#file-babelrc), transform react.

Then there's a production env for transpiling es5  (I still have to support es5 unfortunately).

```json
{
  "env": {
    "production": {
      "presets": ["@babel/preset-env", "@babel/preset-react"],
      "plugins": ["@babel/plugin-proposal-object-rest-spread"]
    },
    "development": {
      "presets": ["@babel/preset-react"]
    }
  }
}
```

Just a last question though, I tried removing `sourcemap: inline,` and it still works, is there a different functionality I'm not aware of opting out of inline source maps? I'm now using `c8` as you recommended, both inline source maps and without give me 100% coverage? 🤗

**Comment by chiefjester** [comment]
By the way, @lorenzofox3 should you ever be open about the idea of babel integration, one advantage is it's going to be less I/O. With this setup, we have to write to disk first before passing the test, on my tests, it almost takes twice the amount to run compared to a similar setup with jest.

Here's jest: 1.45secs
![Alt text](https://monosnap.com/image/Obn4A5PrDw16YORKKDDOI5WxYYqDum)

And here's pta: 
2.14secs
![Alt text](https://monosnap.com/image/7CrsGeaplFoYQKJCcgMwtcfCjXBJZK)

Also note that babel has only need to transpile react on the `pta` version, on the `jest` version it has to transpile down to es5, yet it still faster. I imagine this would be compounded if you have more files to transpile and test. I think the file I/O really plays a big part here.

**Comment by lorenzofox3** [comment]
No, sorry but I won't integrate others tools unrelated to test, there are too many different workflows to have it right without bloating the testing package. 

Most of the transform tools usually come with their own optimization mechanism. What I usually do (with typscript in my case) is to add a ``dev`` script that takes advantages of the watch capabilities of the typescript server whereas the ``test`` script just runs the test. I imagine babel should have similar feature
```
{
    "dev": "tsc -w",
    "test":"time pta"
}
```

pta is almost instant what takes time is to compile/transpile so with this setup the penalty is almost null

**Comment by chiefjester** [comment]
@lorenzofox3 Oh, I'm curious about this setup. I assume `-w` is the watch option? So you're running test, while running dev? Basically having two windows for test and transpiling?

> pta is almost instant what takes time is to compile/transpile so with this setup the penalty is almost null

I guess if you're in dev mode, but you still have to pay for the initial transpiliation, assuming you clone your repo and don't commit your *.js files (basically your src are all *.ts)

This doesn't apply in CI as well. So file I/O does indeed double the time for a test to finish. In fact, I checked back using jest, and just transpile react and modules (since jest doesn't support esm yet like pta).

To my surprise, it actually cut the time in half. **0.71secs** down from **1.45secs.** I guess this is due for not needing to transpile to es5 _(removing preset-env)_. But still doubling the speed 🤯
![Alt text](https://monosnap.com/image/IRorSsLNLfx921SX47Mq19Yne7cGyR)

I'm using this in my `.babelrc` for jest version:
```json
{
  "presets": ["@babel/preset-react"],
  "plugins": ["@babel/plugin-transform-modules-commonjs"]
}
```

**0.71secs** (with babel integration) versus **2.14secs** (pta with babel build), is not just double, but almost triple in this case. And I'm just transpiling two files, imagine if there's more.

I really hope that you think about this, of course, this is your library it's your choice. Just a friendly suggestion.

Thank you for helping me with the setup as earlier. I really appreciate it. 🤗 I'm looking forward to more libraries you release. I'm a big fan of `zora`.

**Comment by chiefjester** [comment]
Some more findings:

`pta's` 'base' speed, it's pretty fast! (assuming I remove c8 and code is already transpiled). **0.42secs**
![Alt text](https://monosnap.com/image/NSPVMNofC38Y3Sj8nekApJRARvOZ1c)

I guess piping coverage also takes time, it clocked at **1.28 seconds**, if I add `c8` before `pta`

**Comment by lorenzofox3** [comment]
Any transformation you add will introduce a penalty (parsing, traversing and transforming the AST, generating the output code). Babel introduces usually a big one. 
``c8`` uses native v8's coverage functionality and will instrument the code as well, so yep it will add some overhead too.

That is why if I work on a project which uses some sort of pre processing, I add a "dev" mode which uses the tool's optimization (caches, etc which eventually limit IO to the strict minimum) so the pre processing is transparent (on file save).
Then from another terminal I run the tests when I need to. Coverage is on its own script too: you don't need to run it every time you run your tests, actually with c8 you can even add coverage threshold for CI ie making the build fail if it does not reach let's say 95%.

You can have a look at the updated gist:
```json
    "build": "babel *.js -d lib",
    "dev": "npm run build -- -w",
    "test": "time pta lib/*.test.js",
    "test:coverage": "c8 pta lib/*.test.js"
```

For non blocking code (pretty current in Javascript, you usually aim at writing non blocking code), ``pta`` will almost always be faster to run the tests than ``Jest``, ``ava``, etc because it does not have to manage child processes (you can fork zora's repository there is some sort of benchmark) and the difference will be greater with the number of test files you have. Of course it depends on the number of core your cpu has, how blocking is your code, etc. That is generally speaking you can have a look at [this article I wrote](https://dev.to/lorenzofox3/there-is-beauty-in-simplicity-1npe)

In your case it does not matter much... you are talking about optimization below a second...

**Comment by chiefjester** [comment]
Hey @lorenzofox3, I just read the article, thank you for sharing how the internals of zora work. I didn't know that Jest has a concurrency of 3 and Ava is 4. While I don't have anything to report. I do get what you are trying to convey in the article on the non-blocking code.

I agree in dev's time relying on external tools like transpiling and coverage is better done in watch mode, removing most of the idle time you wait when you run serially. I did check the links where you use zora on. I guess on CI you still can't take advantage of the "dev mode" since you have to run it [serially](https://github.com/Citykleta/mapboxgl-webcomponent/blob/master/package.json#L19). Anyway thanks for taking the time in explaining to me. I really appreciate it. I guess at the end of the day, it's important you measure and know if it's a good trade-off or not. I still love/will use zora/pta for my projects from time to time. I guess it's also important to continuously re-evaluate your choices as well. 😉

**Comment by lorenzofox3** [comment]
> I didn't know that Jest has a concurrency of 3 and Ava is 4

In that case is more *parallelism* and I think it will differ from one cpu architecture to the other. That's not a golden rule

> I guess on CI you still can't take advantage of the "dev mode" since you have to run it serially

Of course in CI you will have to build your project first. Altogether will it be slower ? I am not even sure. You'll need to download/parse etc 35MB of code before you can use Jest... Does it matter if your CI takes 2s vs 0.5s ?

Note that the tests themselves will still run concurrently, what will be in sequence will be the different build steps as you pointed in the package.json

>I guess it's also important to continuously re-evaluate your choices as well

True, yet I still believe it is not worth it to add a compiler in a test runner ;)

**Comment by chiefjester** [comment]
> Of course in CI you will have to build your project first. Altogether will it be slower ? I am not even sure. You'll need to download/parse etc 35MB of code before you can use Jest... Does it matter if your CI takes 2s vs 0.5s ?

I don't have a straightforward answer for that as well. Going with your benchmark, it makes sense pta will be faster second only to zora, but unit tests are usually lightning fast. I tried pta with jsdom, (react-testing-library) depends on it to make it work. It actually slowed down my test by a large factor. The whole test with coverage and transpile takes about 5 to 6 seconds and this is just testing 2 js files. (I have since made my own renderer, I use cheerio instead of jsdom and it went down to 2 to 3 secs).

As opposed to Jest was doing 1.4seconds. I have to register jsdom's global to node (window and document) and create a blank HTML (in node) to make it work. My point here is Jest has integrated jsdom with their transformer (which can be turned off too), that's probably why they are fast. If we're going by the spirit of your article from dev.to, then those seconds count for DX.

**Comment by lorenzofox3** [comment]
You are probably right, Jest being tailored for React at first, it makes total sense for them to integrate what they think is required in their tester to provide the best experience. 

I could argue that browser applications would be better tested in ...real browsers, not in an emulated environment. 
I could say mock is anti pattern yet it is shipped together with the testing framework.
And the list could go on, that's **opinions** 

At the end it does not matter, Facebook made the choice for you and it seems to be fine for their dev/users so there is not point to argue.

``zora`` and ``pta`` play at a different level where one wants to build its own testing experience based on its actual needs. Example: if one does not need a compiler why would you ship it by default ? There is always a friction between the perfect experience and the trade off you got where someone make the decision for you. 

[I wrote about it](https://dev.to/lorenzofox3/tools-and-the-design-of-a-testing-experience-2mdc) 
and [here you can find an interesting yet different opinion](https://www.jackfranklin.co.uk/blog/letting-tools-make-choices/). 

Over all it seems very few people share my opinions ;)

**Comment by chiefjester** [comment]
Oh, @lorenzofox3 don't get me wrong, I do share your opinions, I'm not just totally black and white. There's always a grey area. You are correct though, opinions would be endless. I'm just sharing my own use case, being general is not bad at all. In fact, React schooled everyone, by shipping just a rendering library. As opposed to what's popular back then where everything is batteries included, Angular and Ember (router, form validation, etc where all built-in). At the end of the day, there are always trade-offs.

I'm also on the side of browser testing. That's what made me use zora in the first place. I know not everyone share's the same opinion as us, but don't let that bother you. zora and pta is a great library. That's why I've been sharing my findings since I want it to succeed. :) Anyway think about it, all I'm asking is making pta extensible by opening up a way to use it with transpiling, adding jsdom or whatever. It doesn't need to live inside pta, it could be just a plugin that people can opt-in too. Making a program extensible is a good thing.

Thank you for your response. I appreciate you sharing your articles with me.

**Comment by chiefjester** [comment]
@lorenzofox3 just read the [article](https://dev.to/lorenzofox3/tools-and-the-design-of-a-testing-experience-2mdc)! It's brilliant, can't wait for the browser version. ✌🏻

**Comment by lorenzofox3** [comment]
[for info on using zora and jsdom](https://github.com/lorenzofox3/zora/issues/56)
